-- MySQL Script generated by MySQL Workbench
-- Fri May  3 15:15:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bibliotecapingu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotecapingu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotecapingu` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bibliotecapingu` ;

-- -----------------------------------------------------
-- Table `bibliotecapingu`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecapingu`.`libro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `area_conocimiento` VARCHAR(100) NOT NULL,
  `numero_paginas` INT NOT NULL,
  `cantidad_ejemplares` INT NOT NULL,
  `cantidad_prestados` INT NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliotecapingu`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecapingu`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(255) NULL DEFAULT NULL,
  `contrasena` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliotecapingu`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecapingu`.`prestamo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_libro` INT NULL DEFAULT NULL,
  `fecha_prestamo` DATE NULL DEFAULT NULL,
  `fecha_devolucion` DATE NULL DEFAULT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `prestamo_ibfk_1` (`id_usuario` ASC) VISIBLE,
  INDEX `prestamo_ibfk_2` (`id_libro` ASC) VISIBLE,
  CONSTRAINT `prestamo_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bibliotecapingu`.`usuario` (`id`),
  CONSTRAINT `prestamo_ibfk_2`
    FOREIGN KEY (`id_libro`)
    REFERENCES `bibliotecapingu`.`libro` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliotecapingu`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecapingu`.`empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(255) NULL DEFAULT NULL,
  `contrasena` VARCHAR(100) NULL DEFAULT NULL,
  `rol` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliotecapingu`.`grabacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecapingu`.`grabacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `genero` VARCHAR(100) NOT NULL,
  `duracion` INT NOT NULL,
  `cantidad_ejemplares` INT NOT NULL,
  `cantidad_prestados` INT NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliotecapingu`.`prestamoG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecapingu`.`prestamoG` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_grabacion` INT NULL DEFAULT NULL,
  `fecha_prestamo` DATE NULL DEFAULT NULL,
  `fecha_devolucion` DATE NULL DEFAULT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `prestamo_ibfk_1` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_grabacion_idx` (`id_grabacion` ASC) VISIBLE,
  CONSTRAINT `prestamo_ibfk_10`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bibliotecapingu`.`usuario` (`id`),
  CONSTRAINT `fk_grabacion`
    FOREIGN KEY (`id_grabacion`)
    REFERENCES `bibliotecapingu`.`grabacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
