-- Poblar tabla libro

INSERT INTO `biblioteca-la-pinguinera`.libro (autor, cantidadDisponible, cantidadEjemplares, cantidadPrestados, titulo, areaDelConocimiento, numeroDePaginas)
VALUES 
	('Gabriel Garcia Márquez', 10, 15, 5, 'Cien anos de soledad', 'Literatura', 432),
	('Agatha Christie', 20, 25, 5, 'Asesinato en el Orient Express', 'Misterio', 256),
    ('Ernest Hemingway', 15, 20, 5, 'El viejo y el mar', 'Ficcion', 112),
    ('F. Scott Fitzgerald', 10, 15, 5, 'El gran Gatsby', 'Ficcion', 180),
    ('Mark Twain', 25, 30, 5, 'Las aventuras de Tom Sawyer', 'Clásico', 224),
    ('Margaret Atwood', 20, 25, 5, 'El cuento de la criada', 'Ficción distópica', 320),
    ('John Steinbeck', 15, 20, 5, 'Las uvas de la ira', 'Ficcion', 464),
    ('Albert Camus', 10, 15, 5, 'El extranjero', 'Ficcion filosófica', 123),
    ('Antoine de Saint-Exupéry', 20, 25, 5, 'El principito', 'Infantil', 96),
    ('Charles Dickens', 25, 30, 5, 'Grandes esperanzas', 'Clásico', 544),
    ('Mary Shelley', 15, 20, 5, 'Frankenstein', 'Ficcion gótica', 280),
    ('Leo Tolstoy', 30, 35, 5, 'Guerra y paz', 'Ficcion histórica', 1225),
    ('Gabriel Garcia Marquez', 25, 30, 5, 'El amor en los tiempos del cólera', 'Ficcion', 368),
    ('J.D. Salinger', 20, 25, 5, 'El guardián entre el centeno', 'Ficción', 224),
    ('Herman Hesse', 10, 15, 5, 'El lobo estepario', 'Ficcion filosófica', 224),
    ('Ray Bradbury', 15, 20, 5, 'Fahrenheit 451', 'Ciencia ficción', 256),
    ('Jorge Luis Borges', 20, 25, 5, 'Ficciones', 'Ficcion', 224),
    ('Haruki Murakami', 25, 30, 5, '1Q84', 'Ficción', 1312),
    ('Virginia Woolf', 15, 20, 5, 'La señora Dalloway', 'Ficción', 194),
    ('Fyodor Dostoevsky', 20, 25, 5, 'Crimen y castigo', 'Ficción', 671),
    ('Roald Dahl', 10, 15, 5, 'Charlie y la fábrica de chocolate', 'Infantil', 208),
    ('Stephen King', 30, 35, 5, 'El resplandor', 'Terror', 512),
    ('Donna Tartt', 15, 20, 5, 'El jilguero', 'Ficción', 864),
    ('Agustín Fernández Paz', 20, 25, 5, 'Cinco panes de cebada', 'Infantil', 176),
    ('Philip K. Dick', 25, 30, 5, 'Blade Runner', 'Ciencia ficción', 210),
    ('Truman Capote', 15, 20, 5, 'A sangre fría', 'No ficción', 368),
    ('Ken Follett', 20, 25, 5, 'Los pilares de la tierra', 'Histórico', 1104),
    ('Sylvia Plath', 10, 15, 5, 'La campana de cristal', 'Ficción', 224),
    ('Douglas Adams', 15, 20, 5, 'Guía del autoestopista galáctico', 'Ciencia ficción', 224),
    ('Terry Pratchett', 20, 25, 5, 'Mort', 'Fantasía', 272),
    ('J.R.R. Tolkien', 15, 20, 5, 'El hobbit', 'Fantasia', 310),
    ('Ernest Hemingway', 18, 22, 4, 'Adiós a las armas', 'Ficcion', 354),
    ('Agatha Christie', 22, 28, 6, 'Diez negritos', 'Misterio', 256),
    ('Herman Melville', 12, 18, 6, 'Moby Dick', 'Clasico', 624),
    ('Franz Kafka', 8, 13, 5, 'La metamorfosis', 'Ficcion', 128),
    ('George Orwell', 19, 23, 4, 'Rebelión en la granja', 'Ciencia ficcion', 112),
    ('Jane Austen', 25, 28, 3, 'Sentido y sensibilidad', 'Ficcion romantica', 328),
    ('H.G. Wells', 17, 22, 5, 'La guerra de los mundos', 'Ciencia ficcion', 192),
    ('Emily Brontë', 13, 18, 5, 'Cumbres borrascosas', 'Romance', 342),
    ('Charles Dickens', 28, 33, 5, 'David Copperfield', 'Clasico', 960),
    ('Arthur Conan Doyle', 16, 21, 5, 'El perro de los Baskerville', 'Misterio', 256),
    ('Bram Stoker', 11, 16, 5, 'Drácula', 'Terror', 448),
    ('William Shakespeare', 30, 35, 5, 'Romeo y Julieta', 'Tragedia', 288),
    ('Jules Verne', 14, 19, 5, 'Veinte mil leguas de viaje submarino', 'Aventura', 504),
    ('Lewis Carroll', 23, 28, 5, 'Alicia en el país de las maravillas', 'Fantasia', 192),
    ('Oscar Wilde', 20, 25, 5, 'El retrato de Dorian Gray', 'Ficcion', 254),
    ('Gustave Flaubert', 18, 23, 5, 'Madame Bovary', 'Ficcion', 432),
    ('Homer', 10, 15, 5, 'La Odisea', 'Epica', 374),
    ('Charlotte Brontë', 15, 20, 5, 'Jane Eyre', 'Ficcion romantica', 490);

    -- Poblar tabla novela

INSERT INTO `biblioteca-la-pinguinera`.novela (autor, cantidadDisponible, cantidadEjemplares, cantidadPrestados, titulo, edadDeLecturaSugerida, genero)
VALUES 
    ('George Orwell', 20, 25, 5, '1984', 16, 'Ciencia ficcion'),
    ('J.R.R. Tolkien', 25, 30, 5, 'El señor de los anillos', 16, 'Fantasia'),
    ('Margaret Atwood', 15, 20, 5, 'El cuento de la criada', 18, 'Ficcion distopica'),
    ('Aldous Huxley', 18, 23, 5, 'Un mundo feliz', 16, 'Ciencia ficcion'),
    ('Ray Bradbury', 22, 27, 5, 'Fahrenheit 451', 16, 'Ciencia ficcion'),
    ('Philip K. Dick', 20, 25, 5, '¿Sueñan los androides con ovejas eléctricas?', 16, 'Ciencia ficcion'),
    ('Stephen King', 30, 35, 5, 'El resplandor', 18, 'Terror'),
    ('J.D. Salinger', 25, 30, 5, 'El guardián entre el centeno', 16, 'Ficcion'),
    ('Harper Lee', 20, 25, 5, 'Matar a un ruiseñor', 16, 'Ficcion'),
    ('Jorge Luis Borges', 18, 23, 5, 'Ficciones', 16, 'Ficcion'),
    ('Fyodor Dostoevsky', 22, 27, 5, 'Crimen y castigo', 18, 'Ficcion'),
    ('Leo Tolstoy', 28, 33, 5, 'Guerra y paz', 18, 'Ficcion'),
    ('Mark Twain', 25, 30, 5, 'Las aventuras de Tom Sawyer', 14, 'Aventura'),
    ('Charles Dickens', 25, 30, 5, 'Grandes esperanzas', 16, 'Ficcion'),
    ('Gabriel Garcia Marquez', 20, 25, 5, 'Cien años de soledad', 18, 'Ficcion'),
    ('Ken Follett', 30, 35, 5, 'Los pilares de la tierra', 18, 'Historico'),
    ('F. Scott Fitzgerald', 18, 23, 5, 'El gran Gatsby', 16, 'Ficcion'),
    ('Ernest Hemingway', 20, 25, 5, 'El viejo y el mar', 16, 'Ficcion'),
    ('John Steinbeck', 25, 30, 5, 'Las uvas de la ira', 16, 'Ficcion'),
    ('Hermann Hesse', 18, 23, 5, 'El lobo estepario', 16, 'Ficcion'),
    ('Gabriel Garcia Marquez', 22, 27, 5, 'El amor en los tiempos del cólera', 18, 'Ficcion'),
    ('Emily Bronte', 20, 25, 5, 'Cumbres borrascosas', 16, 'Ficcion romantica'),
    ('Arthur Conan Doyle', 22, 27, 5, 'El sabueso de los Baskerville', 16, 'Misterio'),
    ('Mary Shelley', 18, 23, 5, 'Frankenstein', 16, 'Ficcion'),
    ('Charlotte Bronte', 22, 27, 5, 'Jane Eyre', 16, 'Ficcion romantica'),
    ('Bram Stoker', 20, 25, 5, 'Dracula', 16, 'Terror'),
    ('Virginia Woolf', 18, 23, 5, 'La señora Dalloway', 16, 'Ficcion'),
    ('Truman Capote', 22, 27, 5, 'A sangre fria', 18, 'No ficcion'),
    ('Albert Camus', 20, 25, 5, 'La peste', 18, 'Ficcion'),
    ('Daniel Keyes', 25, 30, 5, 'Flores para Algernon', 16, 'Ciencia ficcion'),
    ('Kazuo Ishiguro', 22, 27, 5, 'Nunca me abandones', 18, 'Ficcion'),
    ('Roald Dahl', 18, 23, 5, 'Matilda', 10, 'Infantil'),
    ('Isaac Asimov', 25, 30, 5, 'Fundación', 16, 'Ciencia ficcion'),
    ('Gabriel Garcia Marquez', 20, 25, 5, 'El coronel no tiene quien le escriba', 16, 'Ficcion'),
    ('Miguel de Cervantes', 25, 30, 5, 'Don Quijote de la Mancha', 16, 'Clasico'),
    ('Jane Austen', 20, 25, 5, 'Orgullo y prejuicio', 16, 'Ficcion romantica'),
    ('Haruki Murakami', 22, 27, 5, 'Tokio Blues', 18, 'Ficcion'),
    ('Toni Morrison', 22, 27, 5, 'Beloved', 18, 'Ficcion'),
    ('George Orwell', 25, 30, 5, 'Rebelion en la granja', 16, 'Ciencia ficcion'),
    ('Yukio Mishima', 22, 27, 5, 'El marino que perdió la gracia del mar', 18, 'Ficcion'),
    ('Stephen King', 20, 25, 5, 'Cementerio de animales', 18, 'Terror'),
    ('John Steinbeck', 18, 23, 5, 'Al este del eden', 18, 'Ficcion'),
    ('George R.R. Martin', 30, 35, 5, 'Juego de tronos', 18, 'Fantasia'),
    ('Stephen King', 20, 25, 5, 'It', 18, 'Terror'),
    ('Ken Kesey', 25, 30, 5, 'Alguien volo sobre el nido del cuco', 18, 'Ficcion'),
    ('Harper Lee', 18, 23, 5, 'Ve y pon un centinela', 16, 'Ficcion'),
    ('Mario Vargas Llosa', 22, 27, 5, 'La ciudad y los perros', 18, 'Ficcion'),
    ('Gabriel Garcia Marquez', 20, 25, 5, 'El otoño del patriarca', 16, 'Ficcion'),
    ('Kurt Vonnegut', 25, 30, 5, 'Matadero cinco', 16, 'Ciencia ficcion'),
    ('Antoine de Saint-Exupéry', 20, 25, 5, 'Tierra de hombres', 16, 'Ficcion'),
    ('J.D. Salinger', 22, 27, 5, 'Levantad, carpinteros, la viga del tejado y Seymour: una introducción', 16, 'Ficcion');
