-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 14:14:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pinguinera_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pinguinera_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pinguinera_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pinguinera_db` ;

-- -----------------------------------------------------
-- Table `pinguinera_db`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinguinera_db`.`Usuario` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `rol` ENUM("ADMIN", "ASISTENTE", "LECTOR") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pinguinera_db`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinguinera_db`.`Prestamo` (
  `id` VARCHAR(45) NOT NULL,
  `fechaRealizado` DATE NOT NULL,
  `fechaExpiracion` VARCHAR(45) NOT NULL,
  `usuario_id` VARCHAR(45) NOT NULL,
  `estado` ENUM("SOLICITADO", "REALIZADO", "FINALIZADO") NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_Prestamo_Usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `pinguinera_db`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinguinera_db`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinguinera_db`.`Autor` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinguinera_db`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinguinera_db`.`Publicacion` (
  `id` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `nEjemplares` INT NOT NULL,
  `nPrestados` INT NOT NULL,
  `nDisponibles` INT GENERATED ALWAYS AS (nEjemplares - nPrestados) STORED,
  `autor_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `autor_id`),
  INDEX `fk_Publicacion_Autor1_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Publicacion_Autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `pinguinera_db`.`Autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinguinera_db`.`Publicacion x Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinguinera_db`.`Publicacion x Prestamo` (
  `prestamo_id` VARCHAR(45) NOT NULL,
  `publicacion_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prestamo_id`, `publicacion_id`),
  INDEX `fk_Publicacion x Prestamo_Publicacion1_idx` (`publicacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_Publicacion x Prestamo_Prestamo1`
    FOREIGN KEY (`prestamo_id`)
    REFERENCES `pinguinera_db`.`Prestamo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publicacion x Prestamo_Publicacion1`
    FOREIGN KEY (`publicacion_id`)
    REFERENCES `pinguinera_db`.`Publicacion` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinguinera_db`.`Novela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinguinera_db`.`Novela` (
  `id` VARCHAR(45) NOT NULL,
  `edadLectura` INT NOT NULL,
  `genero` ENUM("HISTORICA", "TERROR", "CIENCIA_FICCION", "ROMANTICA") NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Novela_Publicacion1`
    FOREIGN KEY (`id`)
    REFERENCES `pinguinera_db`.`Publicacion` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinguinera_db`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinguinera_db`.`Libro` (
  `id` VARCHAR(45) NOT NULL,
  `paginas` INT NOT NULL,
  `area` ENUM("CIENCIA_POPULAR", "HISTORIA", "BIOGRAFIAS", "ECONOMIA") NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Libro_Publicacion1`
    FOREIGN KEY (`id`)
    REFERENCES `pinguinera_db`.`Publicacion` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
