-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 18:14:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laPinguinera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laPinguinera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laPinguinera` DEFAULT CHARACTER SET utf8 ;
USE `laPinguinera` ;

-- -----------------------------------------------------
-- Table `laPinguinera`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPinguinera`.`Usuario` (
  `correo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laPinguinera`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPinguinera`.`libros` (
  `numeroPaginas` VARCHAR(45) NULL,
  `areaConocimiento` VARCHAR(45) NULL,
  `publicacion_titulo` VARCHAR(45) NOT NULL,
  INDEX `fk_libros_publicacion1_idx` (`publicacion_titulo` ASC) VISIBLE,
  PRIMARY KEY (`publicacion_titulo`),
  CONSTRAINT `fk_libros_publicacion1`
    FOREIGN KEY (`publicacion_titulo`)
    REFERENCES `laPinguinera`.`publicacion` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laPinguinera`.`novelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPinguinera`.`novelas` (
  `edadLecturaSugerida` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `publicacion_titulo` VARCHAR(45) NOT NULL,
  INDEX `fk_novelas_publicacion_idx` (`publicacion_titulo` ASC) VISIBLE,
  PRIMARY KEY (`publicacion_titulo`),
  CONSTRAINT `fk_novelas_publicacion`
    FOREIGN KEY (`publicacion_titulo`)
    REFERENCES `laPinguinera`.`publicacion` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laPinguinera`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPinguinera`.`prestamo` (
  `idPrestamo` INT NOT NULL,
  `fechaEntrega` DATE NULL,
  `fechaDevolucion` DATE NULL,
  `estadoPrestamo` VARCHAR(45) NULL,
  `Usuario_correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_prestamo_Usuario1_idx` (`Usuario_correo` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_Usuario1`
    FOREIGN KEY (`Usuario_correo`)
    REFERENCES `laPinguinera`.`Usuario` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laPinguinera`.`prestamo_libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPinguinera`.`prestamo_libros` (
  `prestamo_idPrestamo` INT NOT NULL,
  `libros_publicacion_titulo` VARCHAR(45) NOT NULL,
  INDEX `fk_prestamo_libros_prestamo1_idx` (`prestamo_idPrestamo` ASC) VISIBLE,
  INDEX `fk_prestamo_libros_libros1_idx` (`libros_publicacion_titulo` ASC) VISIBLE,
  PRIMARY KEY (`libros_publicacion_titulo`),
  CONSTRAINT `fk_prestamo_libros_prestamo1`
    FOREIGN KEY (`prestamo_idPrestamo`)
    REFERENCES `laPinguinera`.`prestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_libros_libros1`
    FOREIGN KEY (`libros_publicacion_titulo`)
    REFERENCES `laPinguinera`.`libros` (`publicacion_titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laPinguinera`.`prestamo_novelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPinguinera`.`prestamo_novelas` (
  `novelas_publicacion_titulo` VARCHAR(45) NOT NULL,
  `prestamo_idPrestamo` INT NOT NULL,
  INDEX `fk_prestamo_novelas_novelas1_idx` (`novelas_publicacion_titulo` ASC) VISIBLE,
  INDEX `fk_prestamo_novelas_prestamo1_idx` (`prestamo_idPrestamo` ASC) VISIBLE,
  PRIMARY KEY (`novelas_publicacion_titulo`),
  CONSTRAINT `fk_prestamo_novelas_novelas1`
    FOREIGN KEY (`novelas_publicacion_titulo`)
    REFERENCES `laPinguinera`.`novelas` (`publicacion_titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_novelas_prestamo1`
    FOREIGN KEY (`prestamo_idPrestamo`)
    REFERENCES `laPinguinera`.`prestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laPinguinera`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPinguinera`.`publicacion` (
  `titulo` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NULL,
  `cantidadDisponible` VARCHAR(45) NULL,
  `cantidadPrestado` VARCHAR(45) NULL,
  `cantidadEjemplates` VARCHAR(45) NULL,
  PRIMARY KEY (`titulo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
