-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 14:54:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LaPinguineraRegresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LaPinguineraRegresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LaPinguineraRegresa` DEFAULT CHARACTER SET utf8 ;
USE `LaPinguineraRegresa` ;

-- -----------------------------------------------------
-- Table `LaPinguineraRegresa`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaPinguineraRegresa`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaPinguineraRegresa`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaPinguineraRegresa`.`Prestamo` (
  `idPrestamo` INT NOT NULL,
  `fechaPrestamo` VARCHAR(45) NULL,
  `fechaDevolucion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `Usuario_correo` VARCHAR(100) NOT NULL,
  `Publicacion_titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_Prestamo_Usuario1_idx` (`Usuario_correo` ASC) VISIBLE,
  INDEX `fk_Prestamo_Publicacion1_idx` (`Publicacion_titulo` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Usuario1`
    FOREIGN KEY (`Usuario_correo`)
    REFERENCES `LaPinguineraRegresa`.`Usuario` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Publicacion1`
    FOREIGN KEY (`Publicacion_titulo`)
    REFERENCES `LaPinguineraRegresa`.`Publicacion` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaPinguineraRegresa`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaPinguineraRegresa`.`Publicacion` (
  `titulo` VARCHAR(45) NOT NULL,
  `tipoPublicacion` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `numPagina` INT NULL,
  `cantEjemplares` INT NULL,
  `cantPrestados` INT NULL,
  `cantDisponible` INT NULL,
  PRIMARY KEY (`titulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaPinguineraRegresa`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaPinguineraRegresa`.`Usuario` (
  `correo` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaPinguineraRegresa`.`areaGenero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaPinguineraRegresa`.`areaGenero` (
  `areaGenero` VARCHAR(45) NOT NULL,
  `Publicacion_titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`areaGenero`, `Publicacion_titulo`),
  INDEX `fk_areaGenero_Publicacion_idx` (`Publicacion_titulo` ASC) VISIBLE,
  CONSTRAINT `fk_areaGenero_Publicacion`
    FOREIGN KEY (`Publicacion_titulo`)
    REFERENCES `LaPinguineraRegresa`.`Publicacion` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LaPinguineraRegresa`.`edadSugerida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaPinguineraRegresa`.`edadSugerida` (
  `edad` VARCHAR(45) NOT NULL,
  `Publicacion_titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`edad`, `Publicacion_titulo`),
  INDEX `fk_edadSugerida_Publicacion1_idx` (`Publicacion_titulo` ASC) VISIBLE,
  CONSTRAINT `fk_edadSugerida_Publicacion1`
    FOREIGN KEY (`Publicacion_titulo`)
    REFERENCES `LaPinguineraRegresa`.`Publicacion` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
